### ISSUE TITLE
Remove the VM from Virtualbox post Vagrant package 

### ISSUE THREAD

**Issue by akshshar** [ios-xr/iosxrv-x64-vbox#7]
I haven't had a chance to look at the code to issue a quick diff.  But we should remove the VM from VirtualBox post "vagrant package" command as part of the cleanup process.
You would need something like:
VBoxmanage unregistervm <VM name> --delete

**Comment by RichWellum** [comment]
I do this when I create the box, so it catches then, but agree it's wise to do it post package. I'm going to add this to my next pull request which is close to going out. (argparse for iosxr_store.py). @akshshar

**Comment by goblinhack** [comment]
is there any way to include the previous context in these emails ?

it's hard to keep track...

neil

**Comment by RichWellum** [comment]
@glennmatthews Not sure tbh Neil @goblinhack . In fact I missed this comment by Akshat @akshshar completely until Glenn tagged me and I don't know why.

**Comment by glennmatthews** [comment]
@RichWellum Are you "watching" this repo? (Top right area of the page)

**Comment by RichWellum** [comment]
Yes I am. Probably just missed the email...

**Comment by glennmatthews** [comment]
Resolved by  7849b8b
